version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    restart: always
    networks:
      - my-bridge-network
      - my-macvlan-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    restart: always
    networks:
      - my-bridge-network

networks:
  my-bridge-network:
    driver: bridge
  my-macvlan-network:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: "192.168.1.0/24"
          gateway: "192.168.1.1"
